@backend_HostAddress = https://localhost:7209

GET {{backend_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{backend_HostAddress}}/weatherforecast

###

POST {{backend_HostAddress}}/api/todo
Content-Type: application/json

{
  //Todo
}

###
